version: "3.4"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - drf-starter.local

  backend:
    build:
      context: backend
    depends_on:
      - db
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_HOST=db
    networks:
      - drf-starter.local
    ports:
      - 80:80
    command: /bin/sh -c "wait-for-it.sh db:5432 -- poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:80 --pythonpath /app/backend"

networks:
  drf-starter.local:
